// ═══════════════════════════════════════════════════════════════
// ERC8257ToolRegistry — TypeScript Bindings (viem/ethers compatible)
// Substrato 889 v2.0 • Generated by ARKHE Cathedral
// ═══════════════════════════════════════════════════════════════

export const ERC8257_ABI = [
  {
    inputs: [
      { name: "_name", type: "string" },
      { name: "_metadataURI", type: "string" },
      { name: "_checksum", type: "bytes32" }
    ],
    name: "registerTool",
    outputs: [{ name: "toolHash", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      { name: "_toolHash", type: "bytes32" },
      { name: "_metadataURI", type: "string" },
      { name: "_checksum", type: "bytes32" }
    ],
    name: "updateTool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      { name: "_toolHash", type: "bytes32" },
      { name: "_expectedChecksum", type: "bytes32" }
    ],
    name: "verifyChecksum",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [{ name: "_toolHash", type: "bytes32" }],
    name: "getTool",
    outputs: [{
      components: [
        { name: "name", type: "string" },
        { name: "metadataURI", type: "string" },
        { name: "checksum", type: "bytes32" },
        { name: "owner", type: "address" },
        { name: "registeredAt", type: "uint256" },
        { name: "exists", type: "bool" }
      ],
      name: "",
      type: "tuple"
    }],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [{ name: "_toolHash", type: "bytes32" }],
    name: "isRegistered",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function"
  }
] as const;

export type ERC8257Tool = {
  name: string;
  metadataURI: string;
  checksum: `0x${string}`;
  owner: `0x${string}`;
  registeredAt: bigint;
  exists: boolean;
};

export type ToolRegisteredEvent = {
  toolHash: `0x${string}`;
  name: string;
  metadataURI: string;
  checksum: `0x${string}`;
  owner: `0x${string}`;
  registeredAt: bigint;
};